---
title: "Project self-assessment of contributions"
subtitle: "2018 Term 2 - MICB425"
output: html_document
---
To facilitate group assessment, please indicate your contributions to the following aspects of your final group reports. You should provide short statements under the headers relevant to your work. For example, you could specify that you "wrote the first draft", "wrote the code to accomplish X figure or result", "troubleshot code", "interpreted results", etc.

Include **separate** completed versions of this document for Project 1 **and** Project 2 in your portfolio repo; they do not need to be incorporated into the final knit portfolio html.

## Abstract
### Writing

### Editing
Edited to include more data & be more succinct

## Introduction
### Literature research

### Writing

### Editing
Provided feedback


## Methods
### Writing
Wrote first draft

### Editing
Made changes according to group feedback
Shortened section to appropriate length

## Results
### Anaysis 
Interpreted results

### Figures
Reorganized plots
Tuned plots to be more visible
Troubleshooted plots

### Writing
Wrote first draft of question 2

### Editing
Combined Results section (separate doc) with other sections & made sure format is consistent
Made sure figure numbers are consistent


## Discussion
### Literature research

### Writing
Wrote some additional ideas

### Editing
Provided feedback